#실제 서비스용 db
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: example
    username: example
    password: example

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        show_sql: none
        ddl-auto: none #ddl비허용 서비스용db는 직접관리
        format_sql: true

  jwt:
    secret: example



server:
  port: example